name = "pocket-reporter"
main = "src/index.ts"
compatibility_date = "2022-10-22"

workers_dev = false

[triggers]
crons = [ "0 15 * * sat" , "0 15 * * fri"  ]

[[queues.producers]]
queue = "slackqueue"
binding = "SQUEUE"