name: check(lint, format)
on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true
      - name: check(lint, format)
        run: pnpm run check